//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppointment
    {
        public int AP_ID { get; set; }
        public Nullable<int> AP_PatientID { get; set; }
        public Nullable<int> AP_DoctorID { get; set; }
        public string AP_Subject { get; set; }
        public string AP_Description { get; set; }
        public Nullable<System.DateTime> AP_Datetime { get; set; }
        public Nullable<bool> AP_IsApproved { get; set; }
        public Nullable<bool> AP_IsUserRead { get; set; }
        public Nullable<bool> AP_IsDoctorRead { get; set; }
        public Nullable<bool> AP_IsActive { get; set; }
        public Nullable<bool> AP_IsArchive { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual tblPatient tblPatient { get; set; }
    }
}
