//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public int A_ID { get; set; }
        public string A_FirstName { get; set; }
        public string A_LastName { get; set; }
        public string A_PhoneNumber { get; set; }
        public Nullable<int> A_AddressID { get; set; }
        public Nullable<int> A_RoleID { get; set; }
        public string A_ProfileImage { get; set; }
        public string A_Email { get; set; }
        public string A_Password { get; set; }
        public Nullable<int> A_CreatedBy { get; set; }
        public Nullable<System.DateTime> A_CreatedOn { get; set; }
        public Nullable<int> A_UpdatedBy { get; set; }
        public Nullable<System.DateTime> A_UpdatedOn { get; set; }
        public Nullable<bool> A_IsActive { get; set; }
        public Nullable<bool> A_IsArchive { get; set; }
        public string A_OTP { get; set; }
        public Nullable<bool> A_Verified { get; set; }
    
        public virtual tblAddress tblAddress { get; set; }
        public virtual tblRole tblRole { get; set; }
    }
}
