//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctorWorkExperience
    {
        public int WEX_ID { get; set; }
        public Nullable<int> WEX_DoctorID { get; set; }
        public string WEX_HospitalName { get; set; }
        public string WEX_Designation { get; set; }
        public Nullable<bool> WEX_IsWorking { get; set; }
        public Nullable<bool> WEX_IsActive { get; set; }
        public Nullable<bool> WEX_IsArchive { get; set; }
        public Nullable<int> WEX_CreatedBy { get; set; }
        public Nullable<System.DateTime> WEX_CreatedOn { get; set; }
        public Nullable<int> WEX_UpdatedBy { get; set; }
        public Nullable<System.DateTime> WEX_UpdatedOn { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
    }
}
