//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiagnostic
    {
        public int DG_ID { get; set; }
        public string DG_Name { get; set; }
        public Nullable<System.DateTime> DG_Datetime { get; set; }
        public Nullable<int> DG_PatientID { get; set; }
        public Nullable<int> DG_DoctorID { get; set; }
        public string DG_DiseaseName { get; set; }
        public string DG_Remarks { get; set; }
        public Nullable<bool> DG_IsActive { get; set; }
        public Nullable<bool> DG_IsArchive { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual tblPatient tblPatient { get; set; }
    }
}
