//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctorReview
    {
        public int DR_ID { get; set; }
        public Nullable<int> DR_DoctorID { get; set; }
        public Nullable<int> DR_PatientID { get; set; }
        public Nullable<int> DR_AppointmentID { get; set; }
        public Nullable<int> DR_DiagnosticsID { get; set; }
        public int DR_StarRatingDiagnostics { get; set; }
        public string DR_Message { get; set; }
        public Nullable<int> DR_RateDoctorService { get; set; }
        public Nullable<bool> DR_IsAllowAnonymous { get; set; }
        public Nullable<bool> DR_IsActive { get; set; }
        public Nullable<bool> DR_IsArchive { get; set; }
        public Nullable<int> DR_CreatedBy { get; set; }
        public Nullable<System.DateTime> DR_CreatedOn { get; set; }
        public Nullable<int> DR_UpdatedBy { get; set; }
        public Nullable<System.DateTime> DR_UpdatedOn { get; set; }
    
        public virtual tblAppointment tblAppointment { get; set; }
        public virtual tblDiagnostic tblDiagnostic { get; set; }
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual tblPatient tblPatient { get; set; }
    }
}
