//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnlineConsultaionDetail
    {
        public int OCD_ID { get; set; }
        public Nullable<int> OCD_DoctorID { get; set; }
        public Nullable<System.TimeSpan> OCD_MondayStartTime { get; set; }
        public Nullable<System.TimeSpan> OCD_MondayEndTime { get; set; }
        public Nullable<System.TimeSpan> OCD_TuesdayStartTime { get; set; }
        public Nullable<System.TimeSpan> OCD_TuesdayEndTime { get; set; }
        public Nullable<System.TimeSpan> OCD_WednesdayStartTime { get; set; }
        public Nullable<System.TimeSpan> OCD_WednesdayEndTime { get; set; }
        public Nullable<System.TimeSpan> OCD_ThursdayStartTime { get; set; }
        public Nullable<System.TimeSpan> OCD_ThursdayEndTime { get; set; }
        public Nullable<System.TimeSpan> OCD_FridayStartTime { get; set; }
        public Nullable<System.TimeSpan> OCD_FridayEndTime { get; set; }
        public Nullable<System.TimeSpan> OCD_SaturdayStartTime { get; set; }
        public Nullable<System.TimeSpan> OCD_SaturdayEndTime { get; set; }
        public Nullable<System.TimeSpan> OCD_SundayStartTime { get; set; }
        public Nullable<System.TimeSpan> OCD_SundayEndTime { get; set; }
        public decimal OCD_Charges { get; set; }
        public Nullable<bool> OCD_IsActive { get; set; }
        public Nullable<bool> OCD_IsArchive { get; set; }
        public Nullable<int> OCD_CreatedBy { get; set; }
        public Nullable<System.DateTime> OCD_CreatedOn { get; set; }
        public Nullable<int> OCD_UpdatedBy { get; set; }
        public Nullable<System.DateTime> OCD_UpdatedOn { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
    }
}
