//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPatient()
        {
            this.tblAppointments = new HashSet<tblAppointment>();
            this.tblDiagnostics = new HashSet<tblDiagnostic>();
            this.tblDoctorReviews = new HashSet<tblDoctorReview>();
            this.tblMessages = new HashSet<tblMessage>();
            this.tblMessages1 = new HashSet<tblMessage>();
            this.tblPatientTests = new HashSet<tblPatientTest>();
        }
    
        public int P_ID { get; set; }
        public string P_FirstName { get; set; }
        public string P_LastName { get; set; }
        public string P_PhoneNumber { get; set; }
        public string P_Gender { get; set; }
        public Nullable<int> P_AddressID { get; set; }
        public Nullable<int> P_RoleID { get; set; }
        public string P_ProfileImage { get; set; }
        public string P_Email { get; set; }
        public string P_Password { get; set; }
        public Nullable<System.DateTime> P_CreatedOn { get; set; }
        public Nullable<int> P_CreatedBy { get; set; }
        public Nullable<System.DateTime> P_UpdatedOn { get; set; }
        public Nullable<int> P_UpdatedBy { get; set; }
        public Nullable<bool> P_IsActive { get; set; }
        public Nullable<bool> P_IsArchive { get; set; }
        public string P_OTP { get; set; }
        public Nullable<bool> P_Verified { get; set; }
    
        public virtual tblAddress tblAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAppointment> tblAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDiagnostic> tblDiagnostics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDoctorReview> tblDoctorReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMessage> tblMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMessage> tblMessages1 { get; set; }
        public virtual tblRole tblRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPatientTest> tblPatientTests { get; set; }
    }
}
